/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaVentaGUI;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import sistemaVentaDAL.Conexion;
import sistemaVentaDAL.Login;

/**
 *
 * @author danie
 */
public class CambiarUsuarioInterfaz extends javax.swing.JFrame {
    

    /**
     * Creates new form CambiarUsuario
     */
    public CambiarUsuarioInterfaz() {
        initComponents();
        this.setLocationRelativeTo(null);//centrar ventana
        this.txtOcultar2.setVisible(false);
    }
    
    public void habilitarBotonGuardar(){
        if((String.valueOf(txtContra.getPassword()).isBlank())  || (txtUsuarioNuevo.getText().isBlank())){
            btnCambiar.setEnabled(false);
        }else {
             btnCambiar.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOcultar2 = new javax.swing.JLabel();
        txtVer2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtUsuarioNuevo = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(98, 133, 254));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cambiar Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 394, 50));

        txtOcultar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocultar.png"))); // NOI18N
        txtOcultar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOcultar2MouseClicked(evt);
            }
        });
        jPanel1.add(txtOcultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 141, 30, 20));

        txtVer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver.png"))); // NOI18N
        txtVer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVer2MouseClicked(evt);
            }
        });
        jPanel1.add(txtVer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 141, 30, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Usuario Nuevo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 88, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 144, -1, -1));

        btnCambiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCambiar.setText("CAMBIAR");
        btnCambiar.setEnabled(false);
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 236, 107, 32));

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 0, 51));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 236, 107, 32));

        txtUsuarioNuevo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtUsuarioNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioNuevoKeyReleased(evt);
            }
        });
        jPanel1.add(txtUsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 86, 187, -1));

        txtContra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContra.setText("213131");
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraKeyReleased(evt);
            }
        });
        jPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 141, 187, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        this.validarContrasena();
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void txtUsuarioNuevoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioNuevoKeyReleased
        this.habilitarBotonGuardar();
    }//GEN-LAST:event_txtUsuarioNuevoKeyReleased

    private void txtOcultar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOcultar2MouseClicked
        txtVer2.setVisible(true);
        txtOcultar2.setVisible(false);
        txtContra.setEchoChar('*');
    }//GEN-LAST:event_txtOcultar2MouseClicked

    private void txtVer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVer2MouseClicked
        txtVer2.setVisible(false);
        txtOcultar2.setVisible(true);
        txtContra.setEchoChar((char)0);
    }//GEN-LAST:event_txtVer2MouseClicked

    private void txtContraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyReleased
        this.habilitarBotonGuardar();
    }//GEN-LAST:event_txtContraKeyReleased
    
    
    
    public void validarContrasena(){
        //Guardar en variables de la clase Login los datos en la base de datos
        Conexion objtConexion = new Conexion();
        Login l = new Login();
        //try catch, para probar traida de datos
        try {
            ResultSet resultado = objtConexion.consultarRegistros("SELECT * from login");
            while (resultado.next()) {
                //Encapsular datos en un objeto
                l.setContrasena(resultado.getString("Password"));
            }
        } catch (Exception e) {
            System.out.println("Error" + e);
        } 
        
        String contrasena = String.valueOf(txtContra.getPassword());
        if(l.validarContrasena(contrasena)){
            actualizarUsuario();
            JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente!!!");
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta \n INTENTE NUEVAMENTE!!!");
            txtContra.setText("");
        }
    }
    
    public void actualizarUsuario(){
        //creación de objetos
        Conexion objtConexion = new Conexion();
        Login l = new Login();
        
        //definir sentencia a enviar
        String strSentenciaEditar = String.format(
                "UPDATE login SET User = '%s'", txtUsuarioNuevo.getText());
        objtConexion.ejecutarSentenciaSQL(strSentenciaEditar);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarUsuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarUsuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarUsuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarUsuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarUsuarioInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JLabel txtOcultar2;
    private javax.swing.JTextField txtUsuarioNuevo;
    private javax.swing.JLabel txtVer2;
    // End of variables declaration//GEN-END:variables
}
