/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaVentaGUI;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import sistemaVentaBL.ClientesBL;
import sistemaVentaDAL.Conexion;
import sistemaVentaDAL.Login;

/**
 *
 * @author danie
 */
public class CambiarContraInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form CambiarContraInterfaz
     */
    public CambiarContraInterfaz() {
        initComponents();
        this.setLocationRelativeTo(null);//centrar ventana
        this.txtOcultar3.setVisible(false);
        this.txtOcultar4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOcultar3 = new javax.swing.JLabel();
        txtVer3 = new javax.swing.JLabel();
        txtVer4 = new javax.swing.JLabel();
        txtOcultar4 = new javax.swing.JLabel();
        btnContraCambiar = new javax.swing.JButton();
        btnContraCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtContraAntigua = new javax.swing.JTextField();
        txtContraNueva = new javax.swing.JPasswordField();
        txtContraConfirmar = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(98, 133, 254));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cambiar Contraseña");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 394, 50));

        txtOcultar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocultar.png"))); // NOI18N
        txtOcultar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOcultar3MouseClicked(evt);
            }
        });
        jPanel1.add(txtOcultar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 125, 30, 22));

        txtVer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver.png"))); // NOI18N
        txtVer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVer3MouseClicked(evt);
            }
        });
        jPanel1.add(txtVer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 125, 30, 22));

        txtVer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ver.png"))); // NOI18N
        txtVer4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVer4MouseClicked(evt);
            }
        });
        jPanel1.add(txtVer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 170, 30, 22));

        txtOcultar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocultar.png"))); // NOI18N
        txtOcultar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOcultar4MouseClicked(evt);
            }
        });
        jPanel1.add(txtOcultar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 170, 30, 22));

        btnContraCambiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnContraCambiar.setText("CAMBIAR");
        btnContraCambiar.setEnabled(false);
        btnContraCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContraCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 235, 107, 32));

        btnContraCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnContraCancelar.setForeground(new java.awt.Color(255, 0, 51));
        btnContraCancelar.setText("CANCELAR");
        btnContraCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContraCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 235, 107, 32));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña Antigua:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 81, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña Nueva:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 126, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Confirmar Nueva:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 172, -1, -1));

        txtContraAntigua.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtContraAntigua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraAntiguaKeyReleased(evt);
            }
        });
        jPanel1.add(txtContraAntigua, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 79, 181, 24));

        txtContraNueva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContraNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraNuevaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraNuevaKeyReleased(evt);
            }
        });
        jPanel1.add(txtContraNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 124, 181, 24));

        txtContraConfirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContraConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraConfirmarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraConfirmarKeyReleased(evt);
            }
        });
        jPanel1.add(txtContraConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 170, 181, 24));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContraCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraCancelarActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_btnContraCancelarActionPerformed
    
    public void habilitarBotonCambiar(){
        if((txtContraAntigua.getText().isBlank())  || (String.valueOf(txtContraConfirmar.getPassword()).isBlank() || (String.valueOf(txtContraNueva.getPassword()).isBlank()))){
            btnContraCambiar.setEnabled(false);
        }else {
             btnContraCambiar.setEnabled(true);
        }
    }
    
    private void btnContraCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraCambiarActionPerformed
        this.validar();
    }//GEN-LAST:event_btnContraCambiarActionPerformed

    private void txtContraAntiguaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraAntiguaKeyReleased
        this.habilitarBotonCambiar();
    }//GEN-LAST:event_txtContraAntiguaKeyReleased

    private void txtVer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVer3MouseClicked
        txtVer3.setVisible(false);
        txtOcultar3.setVisible(true);
        txtContraNueva.setEchoChar((char)0);
    }//GEN-LAST:event_txtVer3MouseClicked

    private void txtVer4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVer4MouseClicked
        txtVer4.setVisible(false);
        txtOcultar4.setVisible(true);
        txtContraConfirmar.setEchoChar((char)0);
    }//GEN-LAST:event_txtVer4MouseClicked

    private void txtOcultar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOcultar3MouseClicked
        txtVer3.setVisible(true);
        txtOcultar3.setVisible(false);
        txtContraNueva.setEchoChar('*');
    }//GEN-LAST:event_txtOcultar3MouseClicked

    private void txtOcultar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOcultar4MouseClicked
        txtVer4.setVisible(true);
        txtOcultar4.setVisible(false);
        txtContraConfirmar.setEchoChar('*');
    }//GEN-LAST:event_txtOcultar4MouseClicked

    private void txtContraNuevaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraNuevaKeyPressed
       
    }//GEN-LAST:event_txtContraNuevaKeyPressed

    private void txtContraConfirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraConfirmarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraConfirmarKeyPressed

    private void txtContraConfirmarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraConfirmarKeyReleased
        this.habilitarBotonCambiar();
    }//GEN-LAST:event_txtContraConfirmarKeyReleased

    private void txtContraNuevaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraNuevaKeyReleased
       this.habilitarBotonCambiar();
    }//GEN-LAST:event_txtContraNuevaKeyReleased
    
    public void validar(){
        if((String.valueOf(txtContraNueva.getPassword()).equals(String.valueOf(txtContraConfirmar.getPassword())))){
            validarContrasena();
        }else if(String.valueOf(txtContraNueva.getPassword()) != String.valueOf(txtContraConfirmar.getPassword())){
            JOptionPane.showMessageDialog(null, "La contraseña nueva no coincide \n INTENTE NUEVAMENTE!!!");
        }
    }
    
    public void validarContrasena(){
        //Guardar en variables de la clase Login los datos en la base de datos
        Conexion objtConexion = new Conexion();
        Login l = new Login();
        //try catch, para probar traida de datos
        try {
            ResultSet resultado = objtConexion.consultarRegistros("SELECT * from login");
            while (resultado.next()) {
                //Encapsular datos en un objeto
                l.setContrasena(resultado.getString("Password"));
            }
        } catch (Exception e) {
            System.out.println("Error" + e);
        } 
        
        String contrasena = txtContraAntigua.getText();
        if(l.validarContrasena(contrasena)){
            actualizarContrasena();
            JOptionPane.showMessageDialog(null, "Contraseña actualizada Correctamente");
            this.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta \n INTENTE NUEVAMENTE!!!");
        }
    }
    
    public void actualizarContrasena(){
        //creación de objetos
        Conexion objtConexion = new Conexion();
        Login l = new Login();
        
        //definir sentencia a enviar
        String strSentenciaEditar = String.format(
                "UPDATE login SET Password = '%s'", String.valueOf(txtContraNueva.getPassword()));
        objtConexion.ejecutarSentenciaSQL(strSentenciaEditar);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContraInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContraCambiar;
    private javax.swing.JButton btnContraCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtContraAntigua;
    private javax.swing.JPasswordField txtContraConfirmar;
    private javax.swing.JPasswordField txtContraNueva;
    private javax.swing.JLabel txtOcultar3;
    private javax.swing.JLabel txtOcultar4;
    private javax.swing.JLabel txtVer3;
    private javax.swing.JLabel txtVer4;
    // End of variables declaration//GEN-END:variables
}
