/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaVentaGUI;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import sistemaVentaBL.ClientesBL;
import sistemaVentaDAL.Conexion;
import sistemaVentaDAL.Login;

/**
 *
 * @author danie
 */
public class CambiarContraInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form CambiarContraInterfaz
     */
    public CambiarContraInterfaz() {
        initComponents();
        this.setLocationRelativeTo(null);//centrar ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnContraCambiar = new javax.swing.JButton();
        btnContraCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtContraAntigua = new javax.swing.JTextField();
        txtContraNueva = new javax.swing.JTextField();
        txtContraConfirmar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel2.setBackground(new java.awt.Color(98, 133, 254));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cambiar Contraseña");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        btnContraCambiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnContraCambiar.setText("CAMBIAR");
        btnContraCambiar.setEnabled(false);
        btnContraCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraCambiarActionPerformed(evt);
            }
        });

        btnContraCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnContraCancelar.setForeground(new java.awt.Color(255, 0, 51));
        btnContraCancelar.setText("CANCELAR");
        btnContraCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña Antigua:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña Nueva:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Confirmar Nueva:");

        txtContraAntigua.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtContraAntigua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraAntiguaKeyReleased(evt);
            }
        });

        txtContraNueva.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtContraNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraNuevaKeyReleased(evt);
            }
        });

        txtContraConfirmar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtContraConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraConfirmarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnContraCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContraAntigua, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtContraNueva)
                            .addComponent(txtContraConfirmar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnContraCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContraAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtContraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContraConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnContraCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnContraCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContraCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraCancelarActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_btnContraCancelarActionPerformed
    
    public void habilitarBotonCambiar(){
        if((txtContraAntigua.getText().isBlank())  || (txtContraConfirmar.getText().isBlank() || (txtContraNueva.getText().isBlank()))){
            btnContraCambiar.setEnabled(false);
        }else {
             btnContraCambiar.setEnabled(true);
        }
    }
    
    private void btnContraCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraCambiarActionPerformed
        this.validar();
    }//GEN-LAST:event_btnContraCambiarActionPerformed

    private void txtContraAntiguaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraAntiguaKeyReleased
        this.habilitarBotonCambiar();
    }//GEN-LAST:event_txtContraAntiguaKeyReleased

    private void txtContraNuevaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraNuevaKeyReleased
         this.habilitarBotonCambiar();
    }//GEN-LAST:event_txtContraNuevaKeyReleased

    private void txtContraConfirmarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraConfirmarKeyReleased
         this.habilitarBotonCambiar();
    }//GEN-LAST:event_txtContraConfirmarKeyReleased
    
    public void validar(){
        if((txtContraNueva.getText().equals(txtContraConfirmar.getText()))){
            validarContrasena();
        }else if(txtContraNueva.getText() != txtContraConfirmar.getText()){
            JOptionPane.showMessageDialog(null, "La contraseña nueva no coincide \n INTENTE NUEVAMENTE!!!");
        }
    }
    
    public void validarContrasena(){
        //Guardar en variables de la clase Login los datos en la base de datos
        Conexion objtConexion = new Conexion();
        Login l = new Login();
        //try catch, para probar traida de datos
        try {
            ResultSet resultado = objtConexion.consultarRegistros("SELECT * from login");
            while (resultado.next()) {
                //Encapsular datos en un objeto
                l.setContrasena(resultado.getString("Password"));
            }
        } catch (Exception e) {
            System.out.println("Error" + e);
        } 
        
        String contrasena = txtContraAntigua.getText();
        if(l.validarContrasena(contrasena)){
            actualizarContrasena();
            JOptionPane.showMessageDialog(null, "Contraseña actualizada Correctamente");
            this.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta \n INTENTE NUEVAMENTE!!!");
        }
    }
    
    public void actualizarContrasena(){
        //creación de objetos
        Conexion objtConexion = new Conexion();
        Login l = new Login();
        
        //definir sentencia a enviar
        String strSentenciaEditar = String.format(
                "UPDATE login SET Password = '%s'", txtContraNueva.getText());
        objtConexion.ejecutarSentenciaSQL(strSentenciaEditar);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContraInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContraCambiar;
    private javax.swing.JButton btnContraCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtContraAntigua;
    private javax.swing.JTextField txtContraConfirmar;
    private javax.swing.JTextField txtContraNueva;
    // End of variables declaration//GEN-END:variables
}
